---
settings:
  name: NetApp SMI-S Provider
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: pt-br,us-en,de-de,es-es,fr-fr,it-it,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: NetApp SMI-S Provider docs
    url: "/index.html"
  - title: Notas de lançamento
    url: "/releasenotes.html"
  - title: Visão geral do fornecedor NetApp SMI-S.
    entries:
    - title: Visão geral
      url: "/concept-overview.html"
    - title: Novidades nesta versão
      url: "/reference-new-in-this-release-smis.html"
    - title: Usos do Fornecedor NetApp SMI-S.
      url: "/reference-uses-of-ontap-smi-s-agent.html"
    - title: Dimensionamento e desempenho do fornecedor NetApp SMI-S
      url: "/reference-smi-s-agent-sizing-and-performance-information.html"
    - title: Componentes do Fornecedor NetApp SMI-S.
      url: "/reference-ontap-smi-s-agent-components.html"
    - title: Protocolos do Fornecedor NetApp SMI-S.
      url: "/reference-ontap-smi-s-agent-protocols.html"
    - title: Como o provedor NetApp SMI-S interage com um host
      url: "/concept-how-smi-s-provider-interacts-with-a-host.html"
    - title: Perfis SMI-S.
      url: "/concept-smi-s-profiles.html"
  - title: Fluxo de trabalho de implantação
    url: "/concept-deployment-workflow.html"
  - title: Prepare-se para a implantação
    entries:
    - title: Visão geral
      url: "/concept-prepare-for-deployment-overview.html"
    - title: Versões suportadas do sistema operativo
      url: "/reference-supported-operating-systems.html"
    - title: Requisitos de hardware
      url: "/reference-hardware-requirements.html"
    - title: Licenças necessárias
      url: "/reference-required-licenses.html"
    - title: Suporte do fornecedor NetApp SMI-S para sistemas ONTAP
      url: "/reference-smi-s-support-ontap-systems.html"
    - title: Transfira o pacote de software do fornecedor NetApp SMI-S
      url: "/task-download-smi-s-provider.html"
  - title: Instale o Fornecedor NetApp SMI-S.
    entries:
    - title: Instale o provedor NetApp SMI-S em um host Windows
      url: "/task-install-smi-s-agent-on-a-windows-host.html"
  - title: Desinstale o Fornecedor NetApp SMI-S.
    entries:
    - title: Desinstalar o NetApp SMI-S Provider de um host Windows
      url: "/task-uninstall-smi-s-agent-from-a-windows-host.html"
  - title: Validação da pré-configuração
    entries:
    - title: Visão geral
      url: "/concept-preconfiguration-task-overview.html"
    - title: Verifique o status do servidor CIM
      url: "/task-verify-the-cim-server-status.html"
    - title: Adicionar um utilizador do servidor CIM
      url: "/task-add-cim-server-users.html"
    - title: Verifique se o sistema de armazenamento está funcionando corretamente
      url: "/task-verify-that-the-storage-system-is-working-correctly.html"
    - title: Gere um certificado auto-assinado para o servidor CIM
      url: "/task-generate-a-self-signed-certificate-for-the-cim-server-windows.html"
  - title: Gerencie o servidor CIM
    url: "/task-manage-the-cim-server.html"
  - title: Gerenciar sistemas de storage
    url: "/task-manage-storage-systems.html"
  - title: Gerenciar usuários do servidor CIM
    entries:
    - title: Visão geral
      url: "/task-manage-cim-server-users-overview.html"
    - title: Tipos de utilizadores CIM e operações associadas
      url: "/reference-types-of-cim-users-and-associated-operations.html"
  - title: Gerir as definições de configuração do CIMOM
    url: "/task-manage-cimom-configuration-settings.html"
  - title: Gerenciar logs e rastreamento
    entries:
    - title: Visão geral
      url: "/concept-manage-logging-and-tracing-overview.html"
    - title: Configure as definições de registo
      url: "/task-configure-log-settings.html"
      entries:
      - title: Níveis de registo
        url: "/reference-logging-levels.html"
    - title: Gerenciar rastreamento
      url: "/concept-manage-tracing.html"
      entries:
      - title: Especifique as definições do traçado
        url: "/task-specify-trace-settings.html"
        entries:
        - title: Valores de definição do traçado
          url: "/reference-trace-setting-values.html"
      - title: Especifique o tamanho do arquivo de rastreamento
        url: "/task-specify-trace-file-size.html"
      - title: Especifique o número de arquivos de rastreamento salvos
        url: "/task-specify-the-number-of-trace-files-saved.html"
    - title: Ativar ou desativar o log de auditoria para comandos SMI-S.
      url: "/task-enable-or-disable-audit-log-for-smi-s-commands.html"
  - title: Gerenciar configurações avançadas do SMI-S Provider
    entries:
    - title: Visão geral
      url: "/concept-manage-smi-s-agent-advanced-settings-overview.html"
    - title: Especifique o intervalo de atualização automática de cache do provedor
        SMI-S
      url: "/task-specify-the-smi-s-agent-cache-refresh-interval.html"
    - title: Especifique o valor de vida útil do trabalho concreto
      url: "/task-specify-the-concrete-job-lifetime-value.html"
    - title: Especifique o valor de tempo limite de chamada da API ONTAP
      url: "/task-specify-the-ontap-api-call-timeout-value.html"
    - title: Especifique o número máximo de threads por fila de serviço de mensagens
      url: "/task-specify-the-maximum-number-of-threads-per-message-service-queue.html"
    - title: Ativar ou desativar a autenticação para o Fornecedor NetApp SMI-S.
      url: "/task-enable-or-disable-authentication-for-smi-s-provider.html"
    - title: Ativar indicações no SMI-S Provider
      url: "/task-enable-indications-in-smi-s-agent.html"
  - title: Gerenciar SLP
    entries:
    - title: Visão geral
      url: "/concept-manage-slp-overview.html"
    - title: Especifique as opções de configuração SLP
      url: "/concept-specify-slp-configuration-options.html"
      entries:
      - title: gerenciamento de arquivos slp.conf
        url: "/reference-editing-the-slp-conf-file.html"
  - title: Comandos CIMOM
    entries:
    - title: cimconfig
      url: "/reference-cimconfig-command-options.html"
  - title: Comandos do utilizador CIM
    entries:
    - title: cimuser
      url: "/reference-cimuser-command-options.html"
  - title: Comandos SMI-S Provider
    entries:
    - title: Visão geral
      url: "/concept-smi-s-provider-commands-overview.html"
    - title: smis add
      url: "/reference-smis-add.html"
    - title: smis addsecure
      url: "/reference-smis-addsecure.html"
    - title: cimom smis
      url: "/reference-smis-cimom.html"
    - title: smis cimserver
      url: "/reference-smis-cimserver.html"
    - title: classe smis
      url: "/reference-smis-class.html"
    - title: show de configuração smis
      url: "/reference-smis-config-show.html"
    - title: smis crp
      url: "/reference-smis-crp.html"
    - title: smis crsp
      url: "/reference-smis-crsp.html"
    - title: eliminar smis
      url: "/reference-smis-delete.html"
    - title: discos smis
      url: "/reference-smis-disks.html"
    - title: exportações smis
      url: "/reference-smis-exports.html"
    - title: iniciadores smis
      url: "/reference-smis-initiators.html"
    - title: smis licenciados
      url: "/reference-smis-licensed.html"
    - title: lista smis
      url: "/reference-smis-list.html"
    - title: luns smis
      url: "/reference-smis-luns.html"
    - title: namespaces smis
      url: "/reference-smis-namespaces.html"
    - title: piscinas smis
      url: "/reference-smis-pools.html"
    - title: atualização de smis
      url: "/reference-smis-refresh.html"
    - title: smis slpd
      url: "/reference-smis-slpd.html"
    - title: versão smis
      url: "/reference-smis-version.html"
    - title: volumes smis
      url: "/reference-smis-volumes.html"
  - title: Comandos SLP
    entries:
    - title: ferramenta de corte
      url: "/reference-slptool-command-options.html"
    - title: slptool findattrs
      url: "/reference-slptool-findattrs.html"
    - title: slptool findsrvs
      url: "/reference-slptool-findsrvs.html"
  - title: Solucionar problemas do provedor SMI-S.
    entries:
    - title: Visão geral
      url: "/concept-troubleshoot-smi-s-agent-overview.html"
    - title: Erro de acesso negado
      url: "/reference-access-is-denied-error.html"
    - title: Possíveis erros ao carregar bibliotecas compartilhadas
      url: "/reference-possible-errors-when-loading-shared-libraries.html"
    - title: Ligação recusada
      url: "/reference-connection-refused-error.html"
    - title: 'Retorno do arquivador: Nenhum elemento ONTAP em resposta'
      url: "/reference-no-ontap-element-in-response-error.html"
    - title: Operações de clone/Snapshot não são permitidas
      url: "/reference-clone-snapshot-operations-are-not-allowed.html"
    - title: Aviso 26130
      url: "/reference-warning-26130.html"
    - title: 'HostAgentAccessDenied (ID: 26263)'
      url: "/reference-hostagentaccessdenied-error-id-26263.html"
    - title: Não é possível ligar ao localhost:5988
      url: "/reference-cannot-connect-to-localhost-5988-error.html"
    - title: Não é possível ligar ao localhost:5989
      url: "/reference-cannot-connect-to-localhost-5989-error.html"
    - title: SMI-S Provider falha no Windows
      url: "/reference-handling-smi-s-agent-crashes-in-windows.html"
    - title: Problema ao inserir senhas contendo carateres especiais
      url: "/reference-entering-passwords-containing-special-characters.html"
    - title: Tecnologia clone usada no SMI-S Provider
      url: "/concept-clone-technology-used-in-smi-s-agent-4-0.html"
    - title: Confirme a visibilidade de objetos importantes
      url: "/concept-confirm-visibility-of-important-objects.html"
    - title: Requisito para usar arquivos no Windows
      url: "/concept-requirement-for-using-fileshares-in-windows.html"
    - title: Firewalls não padrão devem ter portas adicionadas manualmente como exceções
      url: "/reference-non-default-firewalls-must-have-ports-manually-added-as-exceptions.html"
    - title: Não é possível adicionar um sistema de armazenamento usando uma porta
        HTTP ou HTTPS não padrão
      url: "/reference-cannot-add-a-storage-system-using-a-nondefault-http-or-https-port.html"
    - title: Nenhuma resposta do servidor
      url: "/reference-no-response-from-the-server.html"
    - title: Problemas na biblioteca de tempo de execução
      url: "/reference-runtime-library-issues.html"
    - title: O provedor NetApp SMI-S leva muito tempo para começar
      url: "/reference-smi-s-agent-takes-a-long-time-to-start.html"
    - title: Espaço gerenciado total para uma discrepância de pool de armazenamento
        (volume)
      url: "/reference-total-managed-space-for-a-storage-pool-aggregate-discrepancy.html"
    - title: Caminho de rede não encontrado
      url: "/reference-network-path-not-found-error-during-vm-deployment.html"
    - title: Existem recursos do sistema insuficientes para concluir o serviço solicitado
      url: "/reference-vm-provisioning-in-scvmm-fails-with-insufficient-system-resources-error.html"
    - title: Tamanho de compartilhamento SMB caindo para 0 no SCVMM
      url: "/reference-smb-share-size-dropping-to-0-in-scvmm.html"
    - title: A operação de redigitalização SCVMM falhou ao localizar ou se comunicar
        com o Fornecedor SMI-S.
      url: "/reference-scvmm-rescan-operation-failed-to-locate-or-communicate-with-smi-s-provider.html"
  - title: Avisos legais
    url: "/legal-notices.html"
