---
permalink: reference-non-default-firewalls-must-have-ports-manually-added-as-exceptions.html 
sidebar: sidebar 
keywords: troubleshooting, issue, encounter 
summary: Problemas encontrados com o provedor NetApp SMI-S. 
---
= Firewalls não padrão devem ter portas adicionadas manualmente como exceções
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Se você utiliza um firewall diferente do firewall padrão do Windows, o NetApp SMI-S Provider pode não conseguir se comunicar com os clientes ou enviar indicações, a menos que as portas necessárias sejam adicionadas como exceções. Adicione essas portas à configuração do seu firewall para resolver o problema.

* *Emissão*
+
Se você estiver usando um firewall diferente do firewall padrão do Windows, poderá ter os seguintes problemas:

+
** O Fornecedor SMI-S não consegue comunicar com um cliente SMI-S removido.
** O cliente SMI-S não consegue receber indicações do Fornecedor SMI-S.


* *Causa*
+
Esse problema ocorre quando você usa um firewall diferente do firewall padrão do Windows sem primeiro adicionar manualmente as portas necessárias como exceções.

* *Ações corretivas*
+
Adicione as portas 427, 5988 e 5989 como exceções ao seu firewall.


