---
permalink: reference-smis-class.html 
sidebar: sidebar 
keywords: smis class, command, lists, information, 
summary: O comando classe smis lista informações sobre uma classe especificada ou todas as classes. 
---
= classe smis
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
O `smis class` comando lista informações sobre uma classe especificada ou todas as classes.

.Sintaxe
`smis class`

`_name_space_ {*niall*  | {*ei* | *ni* | *gi* | *gc*} _class_name_}} [-t {*http* | *https*}]`

.Localização
`C:\Program Files (x86)\NetApp\smis\pegasus\bin`

.Nível de privilégio
Um utilizador com um nome de utilizador e uma palavra-passe válidos

.Parâmetros
* `*_name_space_*`
+
Espaço de nomes suportado pelo CIMOM

* *niall*
+
Enumerar todos os nomes de instância

* *ei*
+
Enumerar instâncias para uma classe

* *ni*
+
Enumerar nomes de instâncias para uma classe

* *gi*
+
Obtenha instâncias para uma classe

* *gc*
+
Obter classe para um nome de classe

* `*_class_name_*`
+
Nome da classe para a qual você deseja informações

* `*[-t {http | https}]*`
+
Protocolo a ser usado: HTTPS (padrão) ou HTTP



.Exemplo
O `smis class` comando e sua saída abreviada:

[listing]
----
smis class root/ontap gi CIM_StorageVolume
1:
ONTAP_StorageVolume.CreationClassName="ONTAP_StorageVolume",DeviceID="P3LfGJdC-mN5",SystemCreationClassName="ONTAP_StorageSystem",SystemName="ONTAP:0135027815"
2:
ONTAP_StorageVolume.CreationClassName="ONTAP_StorageVolume",DeviceID="P3LfGJcmzpHt",SystemCreationClassName="ONTAP_StorageSystem",SystemName="ONTAP:0135027815"
3:
ONTAP_StorageVolume.CreationClassName="ONTAP_StorageVolume",DeviceID="P3LfGJc30t26",SystemCreationClassName="ONTAP_StorageSystem",SystemName="ONTAP:0135027815"
4:
ONTAP_StorageVolume.CreationClassName="ONTAP_StorageVolume",DeviceID="P3LfGJcSgbiT",SystemCreationClassName="ONTAP_StorageSystem",SystemName="ONTAP:0135027815"
5:
ONTAP_StorageVolume.CreationClassName="ONTAP_StorageVolume",DeviceID="P3LfGJcSgrA9",SystemCreationClassName="ONTAP_StorageSystem",SystemName="ONTAP:0135027815"
----