---
permalink: reference-warning-26130.html 
sidebar: sidebar 
keywords: troubleshooting, issue, encounter 
summary: Problemas encontrados com o provedor NetApp SMI-S. 
---
= Aviso 26130
:allow-uri-read: 
:icons: font
:imagesdir: ./media/




== Mensagem

`Warning (26130) Storage pool has been allocated to host group where none of hosts in host group has access to storage array.`



== Descrição

Esse erro ocorre quando você aloca a capacidade de armazenamento e concede acesso a uma matriz aos hosts que estão em um grupo de hosts. Com este aviso, é impossível colocar máquinas virtuais nos sistemas de armazenamento.



== Ação corretiva

. Em cada máquina host, adicione o endereço IP de cada sistema de armazenamento à aplicação iSCSI Initiator.
. Se necessário, em cada sistema de armazenamento, para cada máquina host, crie um iggroup exclusivo vinculado ao nome de nó iSCSI adequado da máquina host correspondente.
. Para cada máquina host conetada ao Data ONTAP, abra o aplicativo MPIO e adicione o seguinte ID de hardware:
+
** Para Clustered Data ONTAP, digite `*NETAPP LUN C-Mode*`.


. Reinicie as máquinas host.
. Remova o fornecedor.
. Defina o pool de armazenamento novamente.

