---
permalink: reference-cannot-connect-to-localhost-5988-error.html 
sidebar: sidebar 
keywords: troubleshooting, issue, encounter 
summary: Problemas encontrados com o provedor NetApp SMI-S. 
---
= Não é possível ligar ao localhost:5988
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


* *Mensagem*
+
`Cannot connect to localhost:5988. Connection failed. Trying to connect to localhost:5988`

* *Descrição*
+
Esta mensagem ocorre quando as ligações HTTPS estão desativadas ou a porta HTTPS não está definida como 5988, ou se o fornecedor parou de funcionar e permanece num estado de suspensão.

* *Ações corretivas*
+
Verifique se os valores de `enableHttpsConnection` e `httpsPort` estão corretos:

+
`cimconfig -g enableHttpConnection`

+
`cimconfig -g enableHttpsConnection`

+
`cimconfig -g httpPort`

+
`cimconfig -g httpsPort`

+
Se `enableHttpConnection` ou `enableHttpsConnection` não estiver definido como `true`, introduza os seguintes comandos:

+
`cimconfig -s enableHttpConnection -p`

+
`smis cimserver restart`

+
Se `httpPort` não estiver definido como 5988, introduza os seguintes comandos:

+
`cimconfig -s httpPort=5988 -p`

+
`smis cimserver restart`

+
Se o provedor parou de funcionar e permanecer em um estado suspenso, abra o Gerenciador de tarefas e termine o processo e reinicie o provedor.


