---
permalink: reference-supported-operating-systems.html 
sidebar: sidebar 
keywords: installing, smi-s provider, verify, windows, host, operating systems 
summary: Antes de instalar o SMI-S Provider, você deve verificar se o host do Windows está executando um sistema operacional suportado. 
---
= Versões suportadas do sistema operativo
:allow-uri-read: 
:icons: font
:imagesdir: ./media/
:pp: &#43;&#43;


[role="lead"]
Recomendamos que você instale o provedor SMI-S em uma máquina virtual (VM) Windows dedicada. Esta máquina virtual pode estar no mesmo domínio para permitir um gerenciamento seguro e conveniente.

Antes de instalar o SMI-S Provider, você deve verificar se o host do Windows está executando um sistema operacional suportado.

[cols="3*"]
|===
| Sistema operacional | Versões suportadas | Software cliente necessário 


 a| 
Windows
 a| 
* Microsoft Windows Server 2025
* Microsoft Windows Server 2022
* Microsoft Windows Server 2019
* Microsoft Windows Server 2016

 a| 
As bibliotecas de tempo de execução do Microsoft Visual C++ 2010 são instaladas automaticamente durante a instalação do provedor SMI-S. Para evitar possíveis problemas relacionados às bibliotecas de tempo de execução, você deve instalar o Pacote Redistribuível do Microsoft Visual C++ 2010 (x86) a partir do seguinte local: http://www.microsoft.com[]

|===


== Certifique-se de que a máquina host do provedor atenda às especificações.

Para executar o SMI-S Provider, a máquina host do provedor deve atender às seguintes especificações:

* O provedor não pode ser instalado diretamente em um nó Hyper-V. Em vez disso, você pode instalá-lo em uma máquina virtual Hyper-V.
* O System Center Virtual Machine Manager (SCVMM) não deve estar em execução na máquina host do provedor.
* A máquina host do provedor não deve executar outros programas que tenham uso intenso de memória.
* A máquina host do provedor não deve executar provedores SMI-S de nenhum outro fornecedor.

