---
permalink: reference-smb-share-size-dropping-to-0-in-scvmm.html 
sidebar: sidebar 
keywords: troubleshooting, issue, encounter 
summary: Problemas encontrados com o provedor NetApp SMI-S. 
---
= Tamanho de compartilhamento SMB caindo para 0 no SCVMM
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
O tamanho de um compartilhamento SMB 3.0 pode cair para 0 no System Center Virtual Machine Manager (SCVMM) quando a reinicialização da cota demora muito no ONTAP devido à alta atividade de E/S, impedindo o provisionamento de novas VMs. Resolva esse problema ajustando as configurações de cota.

* *Emissão*
+
O tamanho de compartilhamento SMB 3,0 novo ou existente pode cair para 0 no System Center Virtual Machine Manager (SCVMM).

* *Causa*
+
Se a reinicialização da cota levar muito tempo no ONTAP devido a e/S pesadas, o tamanho de compartilhamento SMB 3,0 novo ou existente pode cair para 0 no SCVMM. Quando esse problema ocorre, novas VMs não podem ser provisionadas em compartilhamentos SMB 3,0 novos ou existentes.

* *Ações corretivas*
+
.. Desligue as cotas.
.. Adicione uma regra de cota padrão do tipo "árvore" em cada volume que hospeda compartilhamentos SMB.
.. Ative as cotas para os volumes aos quais você adicionou uma regra de cota padrão e reinicie o provedor SMI-S.



