---
permalink: reference-entering-passwords-containing-special-characters.html 
sidebar: sidebar 
keywords: troubleshooting, issue, encounter 
summary: Problemas encontrados com o provedor NetApp SMI-S. 
---
= Problema ao inserir senhas contendo carateres especiais
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


* *Emissão*
+
Em sistemas operacionais em inglês, usar uma senha que contenha carateres especiais com o `smis` comando não funciona em um ambiente Windows. Este problema não foi testado com sistemas operativos não ingleses.

* *Causa*
+
No Windows, os seguintes carateres, além de quaisquer espaços, são considerados carateres especiais e causam falha na entrada de senha se a senha não estiver entre aspas:

+
, & ' > ; |

* *Ações corretivas*
+
Se uma senha contiver espaços ou carateres especiais, coloque-a em aspas duplas (" ") quando usá-la no `smis` comando. Note que o caractere de citação (") é um caractere especial e nunca deve ser usado em sua senha.





== Emissão de senhas com carateres especiais

`smis add 1.2.3.4 Administrator "pass word"`

`smis add 1.2.3.4 Administrator "pass&word"`
