---
permalink: task-manage-the-cim-server.html 
sidebar: sidebar 
keywords: smi-s provider, start, stop, cim server, review, status 
summary: Pode utilizar o Fornecedor SMI-S para iniciar, parar e reiniciar o servidor CIM e rever o respetivo estado. 
---
= Gerencie o servidor CIM
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Pode utilizar o Fornecedor SMI-S para iniciar, parar e reiniciar o servidor CIM e rever o respetivo estado.

.Antes de começar
* Você já deve ter credenciais de login como Administrador.
* Você já deve ter feito login no sistema host como Administrador.


.Passos
. Acesse o provedor NetApp SMI-S.
. Execute uma das seguintes ações:
+
[cols="3*"]
|===
| Ação | Comando | Informações adicionais 


 a| 
Inicie o servidor CIM
 a| 
`*smis cimserver start*`
 a| 
Depois de introduzir o comando, é apresentada uma mensagem de estado a cada três minutos. Se uma tentativa de alcançar o servidor CIM falhar, mais cinco tentativas são feitas para entrar em Contato com o servidor.



 a| 
Pare o servidor CIM
 a| 
`*smis cimserver stop*`
 a| 
NA



 a| 
Reinicie o servidor CIM
 a| 
`*smis cimserver restart*`
 a| 
NA



 a| 
Ver o estado do servidor CIM
 a| 
`*smis cimserver status*`
 a| 
NA

|===

