---
permalink: task-generate-a-self-signed-certificate-for-the-cim-server-windows.html 
sidebar: sidebar 
keywords: ssl authentication, enable, cim server, installation, self-signed certificate 
summary: Por predefinição, a autenticação SSL está ativada para o servidor CIM. Durante a instalação do Fornecedor SMI-S, um certificado auto-assinado para o servidor CIM é instalado no diretório pegasus. Você pode gerar seu próprio certificado autoassinado e usá-lo em vez do certificado padrão. 
---
= Gere um certificado auto-assinado para o servidor CIM
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Por padrão, a autenticação SSL está habilitada para o servidor CIM. Durante a instalação do provedor SMI-S, um certificado autoassinado para o servidor CIM é instalado no `pegasus` diretório. Você precisa gerar seu próprio certificado autoassinado em vez de usar o certificado padrão.


CAUTION: Ao instalar o provedor SMI-S, o certificado autoassinado padrão instalado estará desatualizado. Como resultado, a conexão SSL com o provedor SMI-S falha ao ser acessada em *Adicionar dispositivos de armazenamento* no System Center Virtual Machine Manager (SCVMM). Você precisa gerar um certificado autoassinado para o servidor CIM e reiniciar o serviço do provedor SMI-S em seguida. Para obter mais informações, consulte link:https://kb.netapp.com/data-mgmt/SMI-S/SMI-S_Issues/CSMIS-3["Artigo da Base de Conhecimento da NetApp : "CSMIS-3: o certificado cimom.cert no NetApp SMI-S Provider 5.2.7 expirou no momento da instalação.""^]

.Antes de começar
* Você já deve ter feito login como Administrador.
* Você já deve ter acessado SMI-S Provider.
* Você deve ter baixado e instalado o OpenSSL em seu computador Windows.


.Passos
. Transfira o `openssl.cnf` ficheiro a partir da seguinte localização: link:http://web.mit.edu/crypto/openssl.cnf["http://web.mit.edu/crypto/openssl.cnf"^]
. Mova o `openssl.cnf` arquivo para o diretório bin:
+
`*%PEGASUS_HOME%\bin\openssl.cnf*`

. Defina a `OPENSSL_CONF` variável ambiental para a localização `openssl.cnf` do arquivo:
+
`*C:\ >set OPENSSL_CONF=%PEGASUS_HOME%\bin\openssl.cnf*`

+
Isso só define a variável de ambiente para a duração da sessão atual do prompt de comando. Se você quiser definir permanentemente a variável de ambiente, você pode usar uma das seguintes opções:

+
** Navegue até *Propriedades > variáveis ambientais* e atualize a variável em *sistema*.
** Use o prompt de comando para definir permanentemente a variável:
+
`*setx OPENSSL_CONF “%PEGASUS_HOME%\bin\openssl.cnf*`.

+
A variável é definida quando você abre uma nova sessão do prompt de comando.



. Navegue até o `%PEGASUS_HOME%\bin` diretório:
+
`*C:\cd %pegasus_home%\bin*`

. Gerar uma chave privada:
+
`*openssl genrsa -out cimom.key 2048*`

. Gerar uma solicitação de certificado:
+
`*openssl req -new -key cimom.key -out cimom.csr*`

. Insira as informações para a solicitação de certificado quando solicitado.
. Gerar o certificado autoassinado:
+
`*openssl x509 -in cimom.csr -out cimom.cert -req -signkey cimom.key -days 1095*`

+
Você pode fornecer um número diferente de dias para os quais o certificado é válido.

. Copie os `cimom.key` ficheiros e `cimom.cert` para o `pegasus` diretório (Windows: `C:\Program Files (x86)\NetApp\smis\pegasus`).
. Reinicie o serviço do provedor SMI-S:
+
`smis cimserver restart`





[[result]]
== Resultado

O intervalo de datas do certificado começa na data atual e é executado pelo número de dias especificados.
